export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAIL = "LOAD_PRODUCTS_FAIL";

export const LOAD_PRODUCTS_BY_ORDER_ID_REQUEST = "LOAD_PRODUCTS_BY_ORDER_ID_REQUEST";
export const LOAD_PRODUCTS_BY_ORDER_ID_SUCCESS = "LOAD_PRODUCTS_BY_ORDER_ID_SUCCESS";
export const LOAD_PRODUCTS_BY_ORDER_ID_FAIL = "LOAD_PRODUCTS_BY_ORDER_ID_FAIL";
